# Generated by Django 5.2.1 on 2025-06-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_read_message_messaging_m_read_d1515a_idx'),
    ]

    operations = [
    ]
